# Site settings
title: Karthik Balakrishnan
email: karthikb351@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Karthik Balakrishnan is a developer by day and activist by night.
  He has been involved with numerous online movements such as
  #SaveTheInternet, ChennaiRains.org.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://karthikbalakrishnan.com" # the base hostname & protocol for your site

owner:
  name: Karthik Balakrishnan
  twitter: karthikb351
  facebook: karthikb351
  github:  karthikb351
  email: karthikb351@gmail.com

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/css/_partials

collections:
  projects:
    output: true
    permalink: /work/:path/

plugins:
  - jekyll-redirect-from
